### ISSUE TITLE
Pinout for better understanding

### ISSUE THREAD

**Issue by patrickschaerer** [myelin/tiny-tft#1]
Hi 
Thanks a lot for your work with those cheap TFTs
I could connect one I bought on aliexpress, but it was hard for me to match your pinnout names to the ones from the Arduino sites. Mabe you could add this to your readme.
Greets 
patrick

Pinout:

1 NC		
2 VSS ________GND
3 LED-________GND
4 LED+_______3.3V
5 VSS________GND
6 /RET________Reset____D8
7 A0__________D/C_______D9
8 SDA________MOSI_____D11
9 SCK________SCK______D13
10 VDDA_____3.3V
11 VDDIC
12 /CS________LCD CS___D10
13 VSS________GND
14 NC

**Comment by myelin** [comment]
Thanks!  I never actually got around to testing out any of the mini TFTs, but I've added your hookup suggestions to https://github.com/myelin/tiny-tft/blob/master/TFT177F254FPC-14-pin-SPI-128x160-1.8-inch/README.md
